# Generated by Django 4.2.16 on 2024-10-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
